############################################################
## This file is generated automatically by Vivado HLS.
## Please DO NOT edit it.
## Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
############################################################
set_directive_unroll "AddRoundKey/AddRoundKey_label0"
set_directive_unroll "AddRoundKey/AddRoundKey_label1"
set_directive_unroll "SubBytes/SubBytes_label2"
set_directive_unroll "SubBytes/SubBytes_label3"
set_directive_unroll "KeyExpansion/KeyExpansion_label0"
set_directive_inline "Cipher"
set_directive_unroll "conv_1dTostate/conv_1dTostate_label0"
set_directive_unroll "conv_1dTostate/conv_1dTostate_label1"
set_directive_unroll "conv_stateTo1d/conv_stateTo1d_label2"
set_directive_unroll "conv_stateTo1d/conv_stateTo1d_label3"
set_directive_unroll "MixColumns/MixColumns_label0"
set_directive_unroll "KeyExpansion/KeyExpansion_label1"
set_directive_inline "ShiftRows"
set_directive_unroll "AES_CTR_xcrypt_buffer/AES_CTR_xcrypt_buffer_label5"
set_directive_inline "Cipher/Cipher_label0"
set_directive_unroll "AES_CBC_decrypt_buffer/AES_CBC_decrypt_buffer_label0"
set_directive_unroll "AES_CBC_encrypt_buffer/AES_CBC_encrypt_buffer_label1"
set_directive_unroll "AES_CTR_xcrypt_buffer/AES_CTR_xcrypt_buffer_label2"
set_directive_unroll "XorWithIv/XorWithIv_label3"
set_directive_unroll "InvSubBytes/InvSubBytes_label4"
set_directive_unroll "InvSubBytes/InvSubBytes_label5"
set_directive_unroll "InvMixColumns/InvMixColumns_label6"
set_directive_inline "xtime"
set_directive_inline "InvCipher/InvCipher_label8"
set_directive_inline "AddRoundKey"
set_directive_inline "SubBytes"
set_directive_unroll "_memcpy/_memcpy_label9"
set_directive_inline "MixColumns"
set_directive_inline "AES_ctx_set_iv"
set_directive_inline "AES_init_ctx_iv"
set_directive_inline "AES_init_ctx"
set_directive_inline "InvMixColumns"
set_directive_inline "InvSubBytes"
set_directive_inline "conv_1dTostate"
set_directive_inline "conv_stateTo1d"
set_directive_inline "InvShiftRows"
set_directive_inline "InvCipher"
set_directive_array_partition -type complete -dim 1 "KeyExpansion" tempa
set_directive_inline "AES_CTR_xcrypt_buffer"
set_directive_inline "KeyExpansion"
