// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "KeyExpansion.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic KeyExpansion::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic KeyExpansion::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<12> KeyExpansion::ap_ST_fsm_state1 = "1";
const sc_lv<12> KeyExpansion::ap_ST_fsm_state2 = "10";
const sc_lv<12> KeyExpansion::ap_ST_fsm_state3 = "100";
const sc_lv<12> KeyExpansion::ap_ST_fsm_state4 = "1000";
const sc_lv<12> KeyExpansion::ap_ST_fsm_state5 = "10000";
const sc_lv<12> KeyExpansion::ap_ST_fsm_state6 = "100000";
const sc_lv<12> KeyExpansion::ap_ST_fsm_state7 = "1000000";
const sc_lv<12> KeyExpansion::ap_ST_fsm_state8 = "10000000";
const sc_lv<12> KeyExpansion::ap_ST_fsm_state9 = "100000000";
const sc_lv<12> KeyExpansion::ap_ST_fsm_state10 = "1000000000";
const sc_lv<12> KeyExpansion::ap_ST_fsm_state11 = "10000000000";
const sc_lv<12> KeyExpansion::ap_ST_fsm_state12 = "100000000000";
const sc_lv<32> KeyExpansion::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> KeyExpansion::ap_const_lv32_1 = "1";
const sc_lv<1> KeyExpansion::ap_const_lv1_0 = "0";
const sc_lv<32> KeyExpansion::ap_const_lv32_2 = "10";
const sc_lv<32> KeyExpansion::ap_const_lv32_3 = "11";
const sc_lv<32> KeyExpansion::ap_const_lv32_4 = "100";
const sc_lv<32> KeyExpansion::ap_const_lv32_6 = "110";
const sc_lv<32> KeyExpansion::ap_const_lv32_7 = "111";
const sc_lv<32> KeyExpansion::ap_const_lv32_8 = "1000";
const sc_lv<1> KeyExpansion::ap_const_lv1_1 = "1";
const sc_lv<32> KeyExpansion::ap_const_lv32_9 = "1001";
const sc_lv<32> KeyExpansion::ap_const_lv32_A = "1010";
const sc_lv<3> KeyExpansion::ap_const_lv3_0 = "000";
const sc_lv<32> KeyExpansion::ap_const_lv32_5 = "101";
const sc_lv<32> KeyExpansion::ap_const_lv32_B = "1011";
const sc_lv<6> KeyExpansion::ap_const_lv6_4 = "100";
const sc_lv<3> KeyExpansion::ap_const_lv3_4 = "100";
const sc_lv<3> KeyExpansion::ap_const_lv3_1 = "1";
const sc_lv<2> KeyExpansion::ap_const_lv2_0 = "00";
const sc_lv<4> KeyExpansion::ap_const_lv4_1 = "1";
const sc_lv<4> KeyExpansion::ap_const_lv4_2 = "10";
const sc_lv<4> KeyExpansion::ap_const_lv4_3 = "11";
const sc_lv<6> KeyExpansion::ap_const_lv6_2C = "101100";
const sc_lv<8> KeyExpansion::ap_const_lv8_FC = "11111100";
const sc_lv<8> KeyExpansion::ap_const_lv8_FD = "11111101";
const sc_lv<6> KeyExpansion::ap_const_lv6_1 = "1";
const sc_lv<8> KeyExpansion::ap_const_lv8_FE = "11111110";
const sc_lv<8> KeyExpansion::ap_const_lv8_FF = "11111111";
const sc_lv<8> KeyExpansion::ap_const_lv8_F0 = "11110000";
const sc_lv<8> KeyExpansion::ap_const_lv8_F1 = "11110001";
const sc_lv<8> KeyExpansion::ap_const_lv8_F2 = "11110010";
const sc_lv<8> KeyExpansion::ap_const_lv8_F3 = "11110011";
const sc_lv<8> KeyExpansion::ap_const_lv8_1 = "1";
const sc_lv<8> KeyExpansion::ap_const_lv8_2 = "10";
const sc_lv<8> KeyExpansion::ap_const_lv8_3 = "11";
const bool KeyExpansion::ap_const_boolean_1 = true;

KeyExpansion::KeyExpansion(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sbox_U = new KeyExpansion_sbox("sbox_U");
    sbox_U->clk(ap_clk);
    sbox_U->reset(ap_rst);
    sbox_U->address0(sbox_address0);
    sbox_U->ce0(sbox_ce0);
    sbox_U->q0(sbox_q0);
    sbox_U->address1(sbox_address1);
    sbox_U->ce1(sbox_ce1);
    sbox_U->q1(sbox_q1);
    Rcon_U = new KeyExpansion_Rcon("Rcon_U");
    Rcon_U->clk(ap_clk);
    Rcon_U->reset(ap_rst);
    Rcon_U->address0(Rcon_address0);
    Rcon_U->ce0(Rcon_ce0);
    Rcon_U->q0(Rcon_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_Key_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln191_fu_355_p1 );
    sensitive << ( zext_ln192_fu_365_p1 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln193_fu_375_p1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln194_fu_385_p1 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_Key_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_Rcon_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln231_fu_481_p1 );

    SC_METHOD(thread_Rcon_ce0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_RoundKey_address0);
    sensitive << ( zext_ln191_reg_636 );
    sensitive << ( zext_ln192_reg_646 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln193_reg_656 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln194_reg_666 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( zext_ln201_fu_410_p1 );
    sensitive << ( zext_ln204_fu_467_p1 );
    sensitive << ( zext_ln247_fu_500_p1 );
    sensitive << ( zext_ln249_fu_558_p1 );
    sensitive << ( zext_ln247_1_fu_584_p1 );
    sensitive << ( zext_ln249_1_fu_616_p1 );

    SC_METHOD(thread_RoundKey_address1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( zext_ln202_fu_421_p1 );
    sensitive << ( zext_ln203_fu_457_p1 );
    sensitive << ( zext_ln246_fu_490_p1 );
    sensitive << ( zext_ln248_fu_548_p1 );
    sensitive << ( zext_ln246_1_fu_575_p1 );
    sensitive << ( zext_ln248_1_fu_606_p1 );

    SC_METHOD(thread_RoundKey_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_RoundKey_ce1);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_RoundKey_d0);
    sensitive << ( Key_q0 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( xor_ln247_reg_794 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( xor_ln249_reg_814 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_RoundKey_d1);
    sensitive << ( xor_ln246_reg_789 );
    sensitive << ( xor_ln248_reg_809 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_RoundKey_we0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_RoundKey_we1);
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_add_ln201_fu_404_p2);
    sensitive << ( j_fu_396_p3 );

    SC_METHOD(thread_add_ln202_fu_415_p2);
    sensitive << ( j_fu_396_p3 );

    SC_METHOD(thread_add_ln203_fu_452_p2);
    sensitive << ( j_reg_679 );

    SC_METHOD(thread_add_ln204_fu_462_p2);
    sensitive << ( j_reg_679 );

    SC_METHOD(thread_add_ln246_fu_485_p2);
    sensitive << ( j_reg_679 );

    SC_METHOD(thread_add_ln247_fu_495_p2);
    sensitive << ( j_reg_679 );

    SC_METHOD(thread_add_ln248_fu_543_p2);
    sensitive << ( j_reg_679 );

    SC_METHOD(thread_add_ln249_fu_553_p2);
    sensitive << ( j_reg_679 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln198_fu_390_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln198_fu_390_p2 );

    SC_METHOD(thread_i_5_fu_446_p2);
    sensitive << ( i_1_reg_320 );

    SC_METHOD(thread_i_fu_337_p2);
    sensitive << ( i_0_reg_309 );

    SC_METHOD(thread_icmp_ln190_fu_331_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_309 );

    SC_METHOD(thread_icmp_ln198_fu_390_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( i_1_reg_320 );

    SC_METHOD(thread_icmp_ln207_fu_430_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln198_fu_390_p2 );
    sensitive << ( trunc_ln198_fu_426_p1 );

    SC_METHOD(thread_j_fu_396_p3);
    sensitive << ( i_1_reg_320 );

    SC_METHOD(thread_or_ln192_fu_360_p2);
    sensitive << ( shl_ln_reg_629 );

    SC_METHOD(thread_or_ln193_fu_370_p2);
    sensitive << ( shl_ln_reg_629 );

    SC_METHOD(thread_or_ln194_fu_380_p2);
    sensitive << ( shl_ln_reg_629 );

    SC_METHOD(thread_or_ln247_fu_579_p2);
    sensitive << ( j_reg_679 );

    SC_METHOD(thread_or_ln248_fu_601_p2);
    sensitive << ( j_reg_679 );

    SC_METHOD(thread_or_ln249_fu_611_p2);
    sensitive << ( j_reg_679 );

    SC_METHOD(thread_sbox_address0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( zext_ln225_fu_472_p1 );
    sensitive << ( zext_ln227_fu_505_p1 );

    SC_METHOD(thread_sbox_address1);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( zext_ln226_fu_476_p1 );
    sensitive << ( zext_ln228_fu_509_p1 );

    SC_METHOD(thread_sbox_ce0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_sbox_ce1);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_shl_ln_fu_347_p3);
    sensitive << ( trunc_ln191_fu_343_p1 );

    SC_METHOD(thread_tempa_0_2_fu_525_p3);
    sensitive << ( icmp_ln207_reg_703 );
    sensitive << ( tempa_0_3_reg_721 );
    sensitive << ( tempa_0_fu_513_p2 );

    SC_METHOD(thread_tempa_0_fu_513_p2);
    sensitive << ( sbox_q0 );
    sensitive << ( Rcon_q0 );

    SC_METHOD(thread_tempa_1_2_fu_519_p3);
    sensitive << ( sbox_q1 );
    sensitive << ( icmp_ln207_reg_703 );
    sensitive << ( tempa_1_reg_727 );

    SC_METHOD(thread_tempa_2_2_fu_569_p3);
    sensitive << ( sbox_q0 );
    sensitive << ( icmp_ln207_reg_703 );
    sensitive << ( tempa_2_reg_743 );

    SC_METHOD(thread_tempa_3_2_fu_563_p3);
    sensitive << ( sbox_q1 );
    sensitive << ( icmp_ln207_reg_703 );
    sensitive << ( tempa_3_reg_748 );

    SC_METHOD(thread_trunc_ln191_fu_343_p1);
    sensitive << ( i_0_reg_309 );

    SC_METHOD(thread_trunc_ln198_fu_426_p1);
    sensitive << ( i_1_reg_320 );

    SC_METHOD(thread_xor_ln246_fu_531_p2);
    sensitive << ( RoundKey_q1 );
    sensitive << ( tempa_0_2_fu_525_p3 );

    SC_METHOD(thread_xor_ln247_fu_537_p2);
    sensitive << ( RoundKey_q0 );
    sensitive << ( tempa_1_2_fu_519_p3 );

    SC_METHOD(thread_xor_ln248_fu_589_p2);
    sensitive << ( RoundKey_q1 );
    sensitive << ( tempa_2_2_fu_569_p3 );

    SC_METHOD(thread_xor_ln249_fu_595_p2);
    sensitive << ( RoundKey_q0 );
    sensitive << ( tempa_3_2_fu_563_p3 );

    SC_METHOD(thread_zext_ln191_fu_355_p1);
    sensitive << ( shl_ln_fu_347_p3 );

    SC_METHOD(thread_zext_ln192_fu_365_p1);
    sensitive << ( or_ln192_fu_360_p2 );

    SC_METHOD(thread_zext_ln193_fu_375_p1);
    sensitive << ( or_ln193_fu_370_p2 );

    SC_METHOD(thread_zext_ln194_fu_385_p1);
    sensitive << ( or_ln194_fu_380_p2 );

    SC_METHOD(thread_zext_ln201_fu_410_p1);
    sensitive << ( add_ln201_fu_404_p2 );

    SC_METHOD(thread_zext_ln202_fu_421_p1);
    sensitive << ( add_ln202_fu_415_p2 );

    SC_METHOD(thread_zext_ln203_fu_457_p1);
    sensitive << ( add_ln203_fu_452_p2 );

    SC_METHOD(thread_zext_ln204_fu_467_p1);
    sensitive << ( add_ln204_fu_462_p2 );

    SC_METHOD(thread_zext_ln225_fu_472_p1);
    sensitive << ( tempa_1_reg_727 );

    SC_METHOD(thread_zext_ln226_fu_476_p1);
    sensitive << ( RoundKey_q1 );

    SC_METHOD(thread_zext_ln227_fu_505_p1);
    sensitive << ( tempa_3_reg_748 );

    SC_METHOD(thread_zext_ln228_fu_509_p1);
    sensitive << ( tempa_0_3_reg_721 );

    SC_METHOD(thread_zext_ln231_fu_481_p1);
    sensitive << ( lshr_ln_reg_711 );

    SC_METHOD(thread_zext_ln246_1_fu_575_p1);
    sensitive << ( j_reg_679 );

    SC_METHOD(thread_zext_ln246_fu_490_p1);
    sensitive << ( add_ln246_fu_485_p2 );

    SC_METHOD(thread_zext_ln247_1_fu_584_p1);
    sensitive << ( or_ln247_fu_579_p2 );

    SC_METHOD(thread_zext_ln247_fu_500_p1);
    sensitive << ( add_ln247_fu_495_p2 );

    SC_METHOD(thread_zext_ln248_1_fu_606_p1);
    sensitive << ( or_ln248_fu_601_p2 );

    SC_METHOD(thread_zext_ln248_fu_548_p1);
    sensitive << ( add_ln248_fu_543_p2 );

    SC_METHOD(thread_zext_ln249_1_fu_616_p1);
    sensitive << ( or_ln249_fu_611_p2 );

    SC_METHOD(thread_zext_ln249_fu_558_p1);
    sensitive << ( add_ln249_fu_553_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln190_fu_331_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( icmp_ln198_fu_390_p2 );

    ap_CS_fsm = "000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "KeyExpansion_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, RoundKey_address0, "(port)RoundKey_address0");
    sc_trace(mVcdFile, RoundKey_ce0, "(port)RoundKey_ce0");
    sc_trace(mVcdFile, RoundKey_we0, "(port)RoundKey_we0");
    sc_trace(mVcdFile, RoundKey_d0, "(port)RoundKey_d0");
    sc_trace(mVcdFile, RoundKey_q0, "(port)RoundKey_q0");
    sc_trace(mVcdFile, RoundKey_address1, "(port)RoundKey_address1");
    sc_trace(mVcdFile, RoundKey_ce1, "(port)RoundKey_ce1");
    sc_trace(mVcdFile, RoundKey_we1, "(port)RoundKey_we1");
    sc_trace(mVcdFile, RoundKey_d1, "(port)RoundKey_d1");
    sc_trace(mVcdFile, RoundKey_q1, "(port)RoundKey_q1");
    sc_trace(mVcdFile, Key_address0, "(port)Key_address0");
    sc_trace(mVcdFile, Key_ce0, "(port)Key_ce0");
    sc_trace(mVcdFile, Key_q0, "(port)Key_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, sbox_address0, "sbox_address0");
    sc_trace(mVcdFile, sbox_ce0, "sbox_ce0");
    sc_trace(mVcdFile, sbox_q0, "sbox_q0");
    sc_trace(mVcdFile, sbox_address1, "sbox_address1");
    sc_trace(mVcdFile, sbox_ce1, "sbox_ce1");
    sc_trace(mVcdFile, sbox_q1, "sbox_q1");
    sc_trace(mVcdFile, Rcon_address0, "Rcon_address0");
    sc_trace(mVcdFile, Rcon_ce0, "Rcon_ce0");
    sc_trace(mVcdFile, Rcon_q0, "Rcon_q0");
    sc_trace(mVcdFile, i_fu_337_p2, "i_fu_337_p2");
    sc_trace(mVcdFile, i_reg_624, "i_reg_624");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, shl_ln_fu_347_p3, "shl_ln_fu_347_p3");
    sc_trace(mVcdFile, shl_ln_reg_629, "shl_ln_reg_629");
    sc_trace(mVcdFile, icmp_ln190_fu_331_p2, "icmp_ln190_fu_331_p2");
    sc_trace(mVcdFile, zext_ln191_fu_355_p1, "zext_ln191_fu_355_p1");
    sc_trace(mVcdFile, zext_ln191_reg_636, "zext_ln191_reg_636");
    sc_trace(mVcdFile, zext_ln192_fu_365_p1, "zext_ln192_fu_365_p1");
    sc_trace(mVcdFile, zext_ln192_reg_646, "zext_ln192_reg_646");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, zext_ln193_fu_375_p1, "zext_ln193_fu_375_p1");
    sc_trace(mVcdFile, zext_ln193_reg_656, "zext_ln193_reg_656");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, zext_ln194_fu_385_p1, "zext_ln194_fu_385_p1");
    sc_trace(mVcdFile, zext_ln194_reg_666, "zext_ln194_reg_666");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, j_fu_396_p3, "j_fu_396_p3");
    sc_trace(mVcdFile, j_reg_679, "j_reg_679");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, icmp_ln198_fu_390_p2, "icmp_ln198_fu_390_p2");
    sc_trace(mVcdFile, icmp_ln207_fu_430_p2, "icmp_ln207_fu_430_p2");
    sc_trace(mVcdFile, icmp_ln207_reg_703, "icmp_ln207_reg_703");
    sc_trace(mVcdFile, lshr_ln_reg_711, "lshr_ln_reg_711");
    sc_trace(mVcdFile, i_5_fu_446_p2, "i_5_fu_446_p2");
    sc_trace(mVcdFile, i_5_reg_716, "i_5_reg_716");
    sc_trace(mVcdFile, tempa_0_3_reg_721, "tempa_0_3_reg_721");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, tempa_1_reg_727, "tempa_1_reg_727");
    sc_trace(mVcdFile, tempa_2_reg_743, "tempa_2_reg_743");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, tempa_3_reg_748, "tempa_3_reg_748");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, xor_ln246_fu_531_p2, "xor_ln246_fu_531_p2");
    sc_trace(mVcdFile, xor_ln246_reg_789, "xor_ln246_reg_789");
    sc_trace(mVcdFile, xor_ln247_fu_537_p2, "xor_ln247_fu_537_p2");
    sc_trace(mVcdFile, xor_ln247_reg_794, "xor_ln247_reg_794");
    sc_trace(mVcdFile, xor_ln248_fu_589_p2, "xor_ln248_fu_589_p2");
    sc_trace(mVcdFile, xor_ln248_reg_809, "xor_ln248_reg_809");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, xor_ln249_fu_595_p2, "xor_ln249_fu_595_p2");
    sc_trace(mVcdFile, xor_ln249_reg_814, "xor_ln249_reg_814");
    sc_trace(mVcdFile, i_0_reg_309, "i_0_reg_309");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, i_1_reg_320, "i_1_reg_320");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, zext_ln201_fu_410_p1, "zext_ln201_fu_410_p1");
    sc_trace(mVcdFile, zext_ln202_fu_421_p1, "zext_ln202_fu_421_p1");
    sc_trace(mVcdFile, zext_ln203_fu_457_p1, "zext_ln203_fu_457_p1");
    sc_trace(mVcdFile, zext_ln204_fu_467_p1, "zext_ln204_fu_467_p1");
    sc_trace(mVcdFile, zext_ln225_fu_472_p1, "zext_ln225_fu_472_p1");
    sc_trace(mVcdFile, zext_ln226_fu_476_p1, "zext_ln226_fu_476_p1");
    sc_trace(mVcdFile, zext_ln231_fu_481_p1, "zext_ln231_fu_481_p1");
    sc_trace(mVcdFile, zext_ln246_fu_490_p1, "zext_ln246_fu_490_p1");
    sc_trace(mVcdFile, zext_ln247_fu_500_p1, "zext_ln247_fu_500_p1");
    sc_trace(mVcdFile, zext_ln227_fu_505_p1, "zext_ln227_fu_505_p1");
    sc_trace(mVcdFile, zext_ln228_fu_509_p1, "zext_ln228_fu_509_p1");
    sc_trace(mVcdFile, zext_ln248_fu_548_p1, "zext_ln248_fu_548_p1");
    sc_trace(mVcdFile, zext_ln249_fu_558_p1, "zext_ln249_fu_558_p1");
    sc_trace(mVcdFile, zext_ln246_1_fu_575_p1, "zext_ln246_1_fu_575_p1");
    sc_trace(mVcdFile, zext_ln247_1_fu_584_p1, "zext_ln247_1_fu_584_p1");
    sc_trace(mVcdFile, zext_ln248_1_fu_606_p1, "zext_ln248_1_fu_606_p1");
    sc_trace(mVcdFile, zext_ln249_1_fu_616_p1, "zext_ln249_1_fu_616_p1");
    sc_trace(mVcdFile, trunc_ln191_fu_343_p1, "trunc_ln191_fu_343_p1");
    sc_trace(mVcdFile, or_ln192_fu_360_p2, "or_ln192_fu_360_p2");
    sc_trace(mVcdFile, or_ln193_fu_370_p2, "or_ln193_fu_370_p2");
    sc_trace(mVcdFile, or_ln194_fu_380_p2, "or_ln194_fu_380_p2");
    sc_trace(mVcdFile, add_ln201_fu_404_p2, "add_ln201_fu_404_p2");
    sc_trace(mVcdFile, add_ln202_fu_415_p2, "add_ln202_fu_415_p2");
    sc_trace(mVcdFile, trunc_ln198_fu_426_p1, "trunc_ln198_fu_426_p1");
    sc_trace(mVcdFile, add_ln203_fu_452_p2, "add_ln203_fu_452_p2");
    sc_trace(mVcdFile, add_ln204_fu_462_p2, "add_ln204_fu_462_p2");
    sc_trace(mVcdFile, add_ln246_fu_485_p2, "add_ln246_fu_485_p2");
    sc_trace(mVcdFile, add_ln247_fu_495_p2, "add_ln247_fu_495_p2");
    sc_trace(mVcdFile, tempa_0_fu_513_p2, "tempa_0_fu_513_p2");
    sc_trace(mVcdFile, tempa_0_2_fu_525_p3, "tempa_0_2_fu_525_p3");
    sc_trace(mVcdFile, tempa_1_2_fu_519_p3, "tempa_1_2_fu_519_p3");
    sc_trace(mVcdFile, add_ln248_fu_543_p2, "add_ln248_fu_543_p2");
    sc_trace(mVcdFile, add_ln249_fu_553_p2, "add_ln249_fu_553_p2");
    sc_trace(mVcdFile, or_ln247_fu_579_p2, "or_ln247_fu_579_p2");
    sc_trace(mVcdFile, tempa_2_2_fu_569_p3, "tempa_2_2_fu_569_p3");
    sc_trace(mVcdFile, tempa_3_2_fu_563_p3, "tempa_3_2_fu_563_p3");
    sc_trace(mVcdFile, or_ln248_fu_601_p2, "or_ln248_fu_601_p2");
    sc_trace(mVcdFile, or_ln249_fu_611_p2, "or_ln249_fu_611_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

KeyExpansion::~KeyExpansion() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete sbox_U;
    delete Rcon_U;
}

void KeyExpansion::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_0_reg_309 = i_reg_624.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_309 = ap_const_lv3_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln190_fu_331_p2.read(), ap_const_lv1_1))) {
        i_1_reg_320 = ap_const_lv6_4;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        i_1_reg_320 = i_5_reg_716.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln198_fu_390_p2.read()))) {
        i_5_reg_716 = i_5_fu_446_p2.read();
        icmp_ln207_reg_703 = icmp_ln207_fu_430_p2.read();
        j_reg_679 = j_fu_396_p3.read();
        lshr_ln_reg_711 = i_1_reg_320.read().range(5, 2);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_624 = i_fu_337_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln190_fu_331_p2.read(), ap_const_lv1_0))) {
        shl_ln_reg_629 = shl_ln_fu_347_p3.read();
        zext_ln191_reg_636 = zext_ln191_fu_355_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        tempa_0_3_reg_721 = RoundKey_q0.read();
        tempa_1_reg_727 = RoundKey_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        tempa_2_reg_743 = RoundKey_q1.read();
        tempa_3_reg_748 = RoundKey_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        xor_ln246_reg_789 = xor_ln246_fu_531_p2.read();
        xor_ln247_reg_794 = xor_ln247_fu_537_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        xor_ln248_reg_809 = xor_ln248_fu_589_p2.read();
        xor_ln249_reg_814 = xor_ln249_fu_595_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        zext_ln192_reg_646 = zext_ln192_fu_365_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        zext_ln193_reg_656 = zext_ln193_fu_375_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        zext_ln194_reg_666 = zext_ln194_fu_385_p1.read();
    }
}

void KeyExpansion::thread_Key_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        Key_address0 =  (sc_lv<4>) (zext_ln194_fu_385_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        Key_address0 =  (sc_lv<4>) (zext_ln193_fu_375_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        Key_address0 =  (sc_lv<4>) (zext_ln192_fu_365_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        Key_address0 =  (sc_lv<4>) (zext_ln191_fu_355_p1.read());
    } else {
        Key_address0 = "XXXX";
    }
}

void KeyExpansion::thread_Key_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        Key_ce0 = ap_const_logic_1;
    } else {
        Key_ce0 = ap_const_logic_0;
    }
}

void KeyExpansion::thread_Rcon_address0() {
    Rcon_address0 =  (sc_lv<4>) (zext_ln231_fu_481_p1.read());
}

void KeyExpansion::thread_Rcon_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        Rcon_ce0 = ap_const_logic_1;
    } else {
        Rcon_ce0 = ap_const_logic_0;
    }
}

void KeyExpansion::thread_RoundKey_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        RoundKey_address0 =  (sc_lv<8>) (zext_ln249_1_fu_616_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        RoundKey_address0 =  (sc_lv<8>) (zext_ln247_1_fu_584_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        RoundKey_address0 =  (sc_lv<8>) (zext_ln249_fu_558_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        RoundKey_address0 =  (sc_lv<8>) (zext_ln247_fu_500_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        RoundKey_address0 =  (sc_lv<8>) (zext_ln204_fu_467_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        RoundKey_address0 =  (sc_lv<8>) (zext_ln201_fu_410_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        RoundKey_address0 =  (sc_lv<8>) (zext_ln194_reg_666.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        RoundKey_address0 =  (sc_lv<8>) (zext_ln193_reg_656.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        RoundKey_address0 =  (sc_lv<8>) (zext_ln192_reg_646.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        RoundKey_address0 =  (sc_lv<8>) (zext_ln191_reg_636.read());
    } else {
        RoundKey_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void KeyExpansion::thread_RoundKey_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        RoundKey_address1 =  (sc_lv<8>) (zext_ln248_1_fu_606_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        RoundKey_address1 =  (sc_lv<8>) (zext_ln246_1_fu_575_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        RoundKey_address1 =  (sc_lv<8>) (zext_ln248_fu_548_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        RoundKey_address1 =  (sc_lv<8>) (zext_ln246_fu_490_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        RoundKey_address1 =  (sc_lv<8>) (zext_ln203_fu_457_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        RoundKey_address1 =  (sc_lv<8>) (zext_ln202_fu_421_p1.read());
    } else {
        RoundKey_address1 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void KeyExpansion::thread_RoundKey_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        RoundKey_ce0 = ap_const_logic_1;
    } else {
        RoundKey_ce0 = ap_const_logic_0;
    }
}

void KeyExpansion::thread_RoundKey_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        RoundKey_ce1 = ap_const_logic_1;
    } else {
        RoundKey_ce1 = ap_const_logic_0;
    }
}

void KeyExpansion::thread_RoundKey_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        RoundKey_d0 = xor_ln249_reg_814.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        RoundKey_d0 = xor_ln247_reg_794.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        RoundKey_d0 = Key_q0.read();
    } else {
        RoundKey_d0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void KeyExpansion::thread_RoundKey_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        RoundKey_d1 = xor_ln248_reg_809.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        RoundKey_d1 = xor_ln246_reg_789.read();
    } else {
        RoundKey_d1 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void KeyExpansion::thread_RoundKey_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        RoundKey_we0 = ap_const_logic_1;
    } else {
        RoundKey_we0 = ap_const_logic_0;
    }
}

void KeyExpansion::thread_RoundKey_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        RoundKey_we1 = ap_const_logic_1;
    } else {
        RoundKey_we1 = ap_const_logic_0;
    }
}

void KeyExpansion::thread_add_ln201_fu_404_p2() {
    add_ln201_fu_404_p2 = (!ap_const_lv8_FC.is_01() || !j_fu_396_p3.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_FC) + sc_biguint<8>(j_fu_396_p3.read()));
}

void KeyExpansion::thread_add_ln202_fu_415_p2() {
    add_ln202_fu_415_p2 = (!ap_const_lv8_FD.is_01() || !j_fu_396_p3.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_FD) + sc_biguint<8>(j_fu_396_p3.read()));
}

void KeyExpansion::thread_add_ln203_fu_452_p2() {
    add_ln203_fu_452_p2 = (!ap_const_lv8_FE.is_01() || !j_reg_679.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_FE) + sc_biguint<8>(j_reg_679.read()));
}

void KeyExpansion::thread_add_ln204_fu_462_p2() {
    add_ln204_fu_462_p2 = (!ap_const_lv8_FF.is_01() || !j_reg_679.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_FF) + sc_biguint<8>(j_reg_679.read()));
}

void KeyExpansion::thread_add_ln246_fu_485_p2() {
    add_ln246_fu_485_p2 = (!ap_const_lv8_F0.is_01() || !j_reg_679.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_F0) + sc_biguint<8>(j_reg_679.read()));
}

void KeyExpansion::thread_add_ln247_fu_495_p2() {
    add_ln247_fu_495_p2 = (!ap_const_lv8_F1.is_01() || !j_reg_679.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_F1) + sc_biguint<8>(j_reg_679.read()));
}

void KeyExpansion::thread_add_ln248_fu_543_p2() {
    add_ln248_fu_543_p2 = (!ap_const_lv8_F2.is_01() || !j_reg_679.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_F2) + sc_biguint<8>(j_reg_679.read()));
}

void KeyExpansion::thread_add_ln249_fu_553_p2() {
    add_ln249_fu_553_p2 = (!ap_const_lv8_F3.is_01() || !j_reg_679.read().is_01())? sc_lv<8>(): (sc_bigint<8>(ap_const_lv8_F3) + sc_biguint<8>(j_reg_679.read()));
}

void KeyExpansion::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void KeyExpansion::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void KeyExpansion::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void KeyExpansion::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void KeyExpansion::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void KeyExpansion::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void KeyExpansion::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void KeyExpansion::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void KeyExpansion::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void KeyExpansion::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void KeyExpansion::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void KeyExpansion::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void KeyExpansion::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
          esl_seteq<1,1,1>(icmp_ln198_fu_390_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void KeyExpansion::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void KeyExpansion::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(icmp_ln198_fu_390_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void KeyExpansion::thread_i_5_fu_446_p2() {
    i_5_fu_446_p2 = (!ap_const_lv6_1.is_01() || !i_1_reg_320.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_1) + sc_biguint<6>(i_1_reg_320.read()));
}

void KeyExpansion::thread_i_fu_337_p2() {
    i_fu_337_p2 = (!i_0_reg_309.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_0_reg_309.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void KeyExpansion::thread_icmp_ln190_fu_331_p2() {
    icmp_ln190_fu_331_p2 = (!i_0_reg_309.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_309.read() == ap_const_lv3_4);
}

void KeyExpansion::thread_icmp_ln198_fu_390_p2() {
    icmp_ln198_fu_390_p2 = (!i_1_reg_320.read().is_01() || !ap_const_lv6_2C.is_01())? sc_lv<1>(): sc_lv<1>(i_1_reg_320.read() == ap_const_lv6_2C);
}

void KeyExpansion::thread_icmp_ln207_fu_430_p2() {
    icmp_ln207_fu_430_p2 = (!trunc_ln198_fu_426_p1.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln198_fu_426_p1.read() == ap_const_lv2_0);
}

void KeyExpansion::thread_j_fu_396_p3() {
    j_fu_396_p3 = esl_concat<6,2>(i_1_reg_320.read(), ap_const_lv2_0);
}

void KeyExpansion::thread_or_ln192_fu_360_p2() {
    or_ln192_fu_360_p2 = (shl_ln_reg_629.read() | ap_const_lv4_1);
}

void KeyExpansion::thread_or_ln193_fu_370_p2() {
    or_ln193_fu_370_p2 = (shl_ln_reg_629.read() | ap_const_lv4_2);
}

void KeyExpansion::thread_or_ln194_fu_380_p2() {
    or_ln194_fu_380_p2 = (shl_ln_reg_629.read() | ap_const_lv4_3);
}

void KeyExpansion::thread_or_ln247_fu_579_p2() {
    or_ln247_fu_579_p2 = (j_reg_679.read() | ap_const_lv8_1);
}

void KeyExpansion::thread_or_ln248_fu_601_p2() {
    or_ln248_fu_601_p2 = (j_reg_679.read() | ap_const_lv8_2);
}

void KeyExpansion::thread_or_ln249_fu_611_p2() {
    or_ln249_fu_611_p2 = (j_reg_679.read() | ap_const_lv8_3);
}

void KeyExpansion::thread_sbox_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        sbox_address0 =  (sc_lv<8>) (zext_ln227_fu_505_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        sbox_address0 =  (sc_lv<8>) (zext_ln225_fu_472_p1.read());
    } else {
        sbox_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void KeyExpansion::thread_sbox_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        sbox_address1 =  (sc_lv<8>) (zext_ln228_fu_509_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        sbox_address1 =  (sc_lv<8>) (zext_ln226_fu_476_p1.read());
    } else {
        sbox_address1 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void KeyExpansion::thread_sbox_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        sbox_ce0 = ap_const_logic_1;
    } else {
        sbox_ce0 = ap_const_logic_0;
    }
}

void KeyExpansion::thread_sbox_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        sbox_ce1 = ap_const_logic_1;
    } else {
        sbox_ce1 = ap_const_logic_0;
    }
}

void KeyExpansion::thread_shl_ln_fu_347_p3() {
    shl_ln_fu_347_p3 = esl_concat<2,2>(trunc_ln191_fu_343_p1.read(), ap_const_lv2_0);
}

void KeyExpansion::thread_tempa_0_2_fu_525_p3() {
    tempa_0_2_fu_525_p3 = (!icmp_ln207_reg_703.read()[0].is_01())? sc_lv<8>(): ((icmp_ln207_reg_703.read()[0].to_bool())? tempa_0_fu_513_p2.read(): tempa_0_3_reg_721.read());
}

void KeyExpansion::thread_tempa_0_fu_513_p2() {
    tempa_0_fu_513_p2 = (Rcon_q0.read() ^ sbox_q0.read());
}

void KeyExpansion::thread_tempa_1_2_fu_519_p3() {
    tempa_1_2_fu_519_p3 = (!icmp_ln207_reg_703.read()[0].is_01())? sc_lv<8>(): ((icmp_ln207_reg_703.read()[0].to_bool())? sbox_q1.read(): tempa_1_reg_727.read());
}

void KeyExpansion::thread_tempa_2_2_fu_569_p3() {
    tempa_2_2_fu_569_p3 = (!icmp_ln207_reg_703.read()[0].is_01())? sc_lv<8>(): ((icmp_ln207_reg_703.read()[0].to_bool())? sbox_q0.read(): tempa_2_reg_743.read());
}

void KeyExpansion::thread_tempa_3_2_fu_563_p3() {
    tempa_3_2_fu_563_p3 = (!icmp_ln207_reg_703.read()[0].is_01())? sc_lv<8>(): ((icmp_ln207_reg_703.read()[0].to_bool())? sbox_q1.read(): tempa_3_reg_748.read());
}

void KeyExpansion::thread_trunc_ln191_fu_343_p1() {
    trunc_ln191_fu_343_p1 = i_0_reg_309.read().range(2-1, 0);
}

void KeyExpansion::thread_trunc_ln198_fu_426_p1() {
    trunc_ln198_fu_426_p1 = i_1_reg_320.read().range(2-1, 0);
}

void KeyExpansion::thread_xor_ln246_fu_531_p2() {
    xor_ln246_fu_531_p2 = (RoundKey_q1.read() ^ tempa_0_2_fu_525_p3.read());
}

void KeyExpansion::thread_xor_ln247_fu_537_p2() {
    xor_ln247_fu_537_p2 = (RoundKey_q0.read() ^ tempa_1_2_fu_519_p3.read());
}

void KeyExpansion::thread_xor_ln248_fu_589_p2() {
    xor_ln248_fu_589_p2 = (RoundKey_q1.read() ^ tempa_2_2_fu_569_p3.read());
}

void KeyExpansion::thread_xor_ln249_fu_595_p2() {
    xor_ln249_fu_595_p2 = (RoundKey_q0.read() ^ tempa_3_2_fu_563_p3.read());
}

void KeyExpansion::thread_zext_ln191_fu_355_p1() {
    zext_ln191_fu_355_p1 = esl_zext<64,4>(shl_ln_fu_347_p3.read());
}

void KeyExpansion::thread_zext_ln192_fu_365_p1() {
    zext_ln192_fu_365_p1 = esl_zext<64,4>(or_ln192_fu_360_p2.read());
}

void KeyExpansion::thread_zext_ln193_fu_375_p1() {
    zext_ln193_fu_375_p1 = esl_zext<64,4>(or_ln193_fu_370_p2.read());
}

void KeyExpansion::thread_zext_ln194_fu_385_p1() {
    zext_ln194_fu_385_p1 = esl_zext<64,4>(or_ln194_fu_380_p2.read());
}

void KeyExpansion::thread_zext_ln201_fu_410_p1() {
    zext_ln201_fu_410_p1 = esl_zext<64,8>(add_ln201_fu_404_p2.read());
}

void KeyExpansion::thread_zext_ln202_fu_421_p1() {
    zext_ln202_fu_421_p1 = esl_zext<64,8>(add_ln202_fu_415_p2.read());
}

void KeyExpansion::thread_zext_ln203_fu_457_p1() {
    zext_ln203_fu_457_p1 = esl_zext<64,8>(add_ln203_fu_452_p2.read());
}

void KeyExpansion::thread_zext_ln204_fu_467_p1() {
    zext_ln204_fu_467_p1 = esl_zext<64,8>(add_ln204_fu_462_p2.read());
}

void KeyExpansion::thread_zext_ln225_fu_472_p1() {
    zext_ln225_fu_472_p1 = esl_zext<64,8>(tempa_1_reg_727.read());
}

void KeyExpansion::thread_zext_ln226_fu_476_p1() {
    zext_ln226_fu_476_p1 = esl_zext<64,8>(RoundKey_q1.read());
}

void KeyExpansion::thread_zext_ln227_fu_505_p1() {
    zext_ln227_fu_505_p1 = esl_zext<64,8>(tempa_3_reg_748.read());
}

void KeyExpansion::thread_zext_ln228_fu_509_p1() {
    zext_ln228_fu_509_p1 = esl_zext<64,8>(tempa_0_3_reg_721.read());
}

void KeyExpansion::thread_zext_ln231_fu_481_p1() {
    zext_ln231_fu_481_p1 = esl_zext<64,4>(lshr_ln_reg_711.read());
}

void KeyExpansion::thread_zext_ln246_1_fu_575_p1() {
    zext_ln246_1_fu_575_p1 = esl_zext<64,8>(j_reg_679.read());
}

void KeyExpansion::thread_zext_ln246_fu_490_p1() {
    zext_ln246_fu_490_p1 = esl_zext<64,8>(add_ln246_fu_485_p2.read());
}

void KeyExpansion::thread_zext_ln247_1_fu_584_p1() {
    zext_ln247_1_fu_584_p1 = esl_zext<64,8>(or_ln247_fu_579_p2.read());
}

void KeyExpansion::thread_zext_ln247_fu_500_p1() {
    zext_ln247_fu_500_p1 = esl_zext<64,8>(add_ln247_fu_495_p2.read());
}

void KeyExpansion::thread_zext_ln248_1_fu_606_p1() {
    zext_ln248_1_fu_606_p1 = esl_zext<64,8>(or_ln248_fu_601_p2.read());
}

void KeyExpansion::thread_zext_ln248_fu_548_p1() {
    zext_ln248_fu_548_p1 = esl_zext<64,8>(add_ln248_fu_543_p2.read());
}

void KeyExpansion::thread_zext_ln249_1_fu_616_p1() {
    zext_ln249_1_fu_616_p1 = esl_zext<64,8>(or_ln249_fu_611_p2.read());
}

void KeyExpansion::thread_zext_ln249_fu_558_p1() {
    zext_ln249_fu_558_p1 = esl_zext<64,8>(add_ln249_fu_553_p2.read());
}

void KeyExpansion::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln190_fu_331_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(icmp_ln198_fu_390_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<12>) ("XXXXXXXXXXXX");
            break;
    }
}

}

